### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by enniosalomone** [Salvatorem89/TreasureHunt#10]
In travis-ci.com non riusciamo a vedere gli ultimi commit. L'ultimo commit visibile è il 49 e perciò tenta di fare la build solo di quella versione della repository. Non riusciamo a cambiare il commit da buildare e perciò non riusciamo a capire se travis funzione o meno.

**Comment by Salvatorem89** [comment]
Build di travis aggiornata tramite il comando trigger build.
