### ISSUE TITLE
Cattura del tempo totale

### ISSUE THREAD

**Issue by enricodicerbo** [Salvatorem89/TreasureHunt#7]
Quando una sfida viene completata con successo il tempo totale impiegato risulta essere sempre lo stesso a prescindere dal comportamento dell'hunter.

**Comment by enniosalomone** [comment]
Nel passaggio da un'activity all'altra si passava la variabile si inizio sfida come un Long e si chiedeva la sua ricezione con un metodo GetInt. Questo causava un errore nel calcolo del tempo della sfida.
